name: obserability-dashboard-newrelic
run-name: Dashboard build - ${{ github.actor }}
on: [push]
jobs:
  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Workspace
        run: |
          terraform version
          terraform init
          terraform workspace new prod
          terraform workspace select prod
          terraform workspace list
      - name: Lint
        run: |
          cd ${{ github.workspace }}
          terraform fmt --recursive
