name: obserability-dashboard-newrelic
run-name: Dashboard build - ${{ github.actor }}
on: [push]
jobs:
  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Lint
        uses: dflook/terraform-fmt-check@v1
        id: tf-lint-result
        with:
          path: ${{ github.workspace }}

      - name: Check Lint Result
        if: ${{ failure() && steps.tf-lint-result.outputs.failure-reason == 'check-failed' }}
        run | 
          echo "Terraform formatting check failed"
          return 1      

      - name: Setup Terraform Workspace
        run: |
          terraform version
          terraform init
          terraform workspace new prod
          terraform workspace select prod
          terraform workspace list
      - name: Lint
        run: |
          cd ${{ github.workspace }}
          terraform fmt --recursive
