name: obserability-dashboard-newrelic
run-name: Dashboard build - ${{ github.actor }}
on: [push]
jobs:
  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - run: terraform version
      - name: Setup Workspace
        run: terraform init
        run: terraform workspace new prod
        run: terraform workspace select prod
        run: terraform workspace list
      - name: Lint
        run: cd ${{ github.workspace }}
        run: terraform fmt --recursive
